### ISSUE TITLE
Bug : Error when not selecting any option in console version

### ISSUE THREAD

**Issue by Anindra123** [luiz-diniz/PasswordGenerator#3]
Selecting each option as false on the console app gives an unhandled exception.

```
Unhandled exception. System.ArgumentOutOfRangeException: Index and length must refer to a location within the string. (Parameter 'length')
   at System.String.Substring(Int32 startIndex, Int32 length)
   at PasswordGenerator.Core.PasswordGeneratorManager.Generate(PasswordOptions passwordOptions) in D:\C#\PasswordGenerator\PasswordGenerator\PasswordGenerator.Core\PasswordGeneratorManager.cs:line 45
   at PasswordGenerator.Core.PasswordGeneratorManager.GeneratePassword(PasswordOptions passwordOptions) in D:\C#\PasswordGenerator\PasswordGenerator\PasswordGenerator.Core\PasswordGeneratorManager.cs:line 24
   at PasswordGenerator.ConsoleApp.Program.Main(String[] args) in D:\C#\PasswordGenerator\PasswordGenerator\PasswordGenerator.ConsoleApp\Program.cs:line 38
   
 ```

**Comment by luiz-diniz** [comment]
That's correct, I just tested here and caught the same error. 
I'll work on this later.

Thanks!

**Comment by luiz-diniz** [comment]
Issue treated on commit "52add78026b8e111163470a51efa7416c0d159cb"
